// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSS1HzuyYj0mqvrnHSMUt2bvXaGpw54k',
    appId: '1:655637695133:web:bdae4b10c067f4d422a274',
    messagingSenderId: '655637695133',
    projectId: 'flutter-chat-app-6eefe',
    authDomain: 'flutter-chat-app-6eefe.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6eefe.appspot.com',
    measurementId: 'G-ZPRH86RZ51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nbCR9H3wVsTBaNsh4l5WBHw2WHeq0mI',
    appId: '1:655637695133:android:4aaecd0b597e939422a274',
    messagingSenderId: '655637695133',
    projectId: 'flutter-chat-app-6eefe',
    storageBucket: 'flutter-chat-app-6eefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtmYV_rerVgIbT7OrNNNYp_5VrawqBkk',
    appId: '1:655637695133:ios:79674fb9e528d68122a274',
    messagingSenderId: '655637695133',
    projectId: 'flutter-chat-app-6eefe',
    storageBucket: 'flutter-chat-app-6eefe.appspot.com',
    iosBundleId: 'com.example.mixiTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtmYV_rerVgIbT7OrNNNYp_5VrawqBkk',
    appId: '1:655637695133:ios:79674fb9e528d68122a274',
    messagingSenderId: '655637695133',
    projectId: 'flutter-chat-app-6eefe',
    storageBucket: 'flutter-chat-app-6eefe.appspot.com',
    iosBundleId: 'com.example.mixiTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANSS1HzuyYj0mqvrnHSMUt2bvXaGpw54k',
    appId: '1:655637695133:web:f9bec7015d37af8a22a274',
    messagingSenderId: '655637695133',
    projectId: 'flutter-chat-app-6eefe',
    authDomain: 'flutter-chat-app-6eefe.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6eefe.appspot.com',
    measurementId: 'G-XWQMEEV0GL',
  );
}
